sudo: false

addons:
    apt:
      packages:
       - make
       - cmake-data
       - cmake
       - libglu1-mesa-dev
       - libgl1-mesa-dev 

matrix:
    include:
    - os: linux
      language: c++
      install: true
    - os: osx
      language: c++
      osx_image: xcode9.2
      install: true

cache:
  ccache: true
  directories:
   - $HOME/Library/Caches/Homebrew
   - $HOME/.ccache
   # TODO: how can we do conditional caching of directories (depending on OS)
   #- /home/travis/build/miho/OCC-CSG/oce-OCE-0.18.3
   - /Users/travis/build/miho/occ-for-occ-csg/opencascade
   - /Users/travis/build/miho/occ-for-occ-csg/dependencies

env:
  global:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then PATH=/usr/lib/ccache:${PATH}; fi
    - TIMEOUT_BUILD='30m'
    - BUILD_SUCCESS=true
    
before_install:
  # installing ccache and freetype packages via homebrew
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ccache; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
  # adding timeout command to path for os x
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then PATH="$PATH:/usr/local/opt/coreutils/libexec/gnubin"; fi
  
script: 
    - export OUR_DIR=$(pwd)
    - echo "home directory $OUR_DIR"
    
    # downloading and building static freetype
    #- wget https://download.savannah.gnu.org/releases/freetype/freetype-2.7.1.tar.gz
    #- tar xzf freetype-2.7.1.tar.gz
    #- cd freetype-2.7.1; mkdir -p build; cd build;
    - mkdir -p $OUR_DIR/dependencies-installation/freetype
    - cd $OUR_DIR/dependencies/freetype  
    - mkdir -p build; cd build;
    - cmake .. -DWITH_ZLIB=OFF -DWITH_HarfBuzz=OFF -DWITH_PNG=OFF -DWITH_BZip2=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=$OUR_DIR/dependencies-installation/freetype;
    - make -j2 && make install
    - cd $OUR_DIR
    
    # downloading OCE
    #- if [ ! -f OCE-0.18.3.tar.gz ]; then wget https://github.com/miho/oce/archive/OCE-0.18.3.tar.gz; fi
    #- if [ ! -f oce-OCE-0.18.3 ]; then tar xzf OCE-0.18.3.tar.gz; fi
    #- cd oce-OCE-0.18.3
    - cd opencascade
    - mkdir -p build && mkdir -p $OUR_DIR/opencascade-installation && cd build
    
    # setting OCE install dir
    # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export OCE_INSTALL_DIR=$(pwd)/../opencascade-installation/OCE.framework/Versions/0.18/Resources; fi
    # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export OCE_INSTALL_DIR=$(pwd)/../opencascade-installation/lib/oce-0.18/; fi
    
    # configuring OCE via cmake
    - cmake .. -DBUILD_LIBRARY_TYPE:String="Static" -DCMAKE_BUILD_TYPE=Release -DBUILD_MODULE_Draw:BOOL=false -D3RDPARTY_DIR=$OUR_DIR/dependencies-installation -DCMAKE_INSTALL_PREFIX=$OUR_DIR/opencascade-installation -DINSTALL_FREETYPE:BOOL=true
    
    # now we build OCE
    # -> On macOS we use a timeout to prevent travis from terminating our build job
    #    without saving the ccache and OCE directories. We rerun the job until OCE
    #    is fully built. The output will indicate that by showing 
    #       ">> skipping build until ccache and compilation of oce works. restart task or schedule new task."
    #    TODO: is there a workaround for build jobs that take longer than 50 minutes?
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then travis_wait 30 make -j4 || export BUILD_SUCCESS=false ; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_wait 30 make -j4 || export BUILD_SUCCESS=false ; fi
    - if [ "$BUILD_SUCCESS" == true ]; then echo "INSTALL"; make install > install_out.txt ; fi

    # show last 30 lines of install output
    - tail -n 30 install_out.txt
    
    - if [ "$BUILD_SUCCESS" != true ]; then echo ">> skipping build until ccache and compilation of occ works. restart task or schedule new task."; fi
    
    - echo "HOME:" && ls $OUR_DIR
    
    - echo "INSTALL:"
    - ls $OUR_DIR/opencascade-installation/
    
    
    # finally build and test occ-csg
    #- cd $OUR_DIR
    #- mkdir -p build && cd build
    #- (! $BUILD_SUCCESS && echo ">> skipping build until ccache and compilation of oce works. restart task or schedule new task.") || cmake .. -DOCE_DIR=$OCE_INSTALL_DIR
    #- (! $BUILD_SUCCESS && echo ">> skipping build until ccache and compilation of oce works. restart task or schedule new task.") || make && bin/occ-csg --help       

before_deploy:
    - cd $OUR_DIR
    - mkdir release && cd release
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir -p opencascade-$TRAVIS_TAG-macos/; cp -r $OUR_DIR/opencascade-installation/* opencascade-$TRAVIS_TAG-macos; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then zip -r opencascade-$TRAVIS_TAG-macos.zip opencascade-$TRAVIS_TAG-macos/; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir -p opencascade-$TRAVIS_TAG-linux-x64/; cp -r $OUR_DIR/opencascade-installation/* opencascade-$TRAVIS_TAG-linux-x64/; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then zip -r opencascade-$TRAVIS_TAG-linux-x64.zip opencascade-$TRAVIS_TAG-linux-x64/; fi   

deploy:
    - provider: releases
    
      api_key:
        secure: viIrz01hHL97XF1B2Dq37VkaOjaenpP0bWYXeFXBiCd6a1tBYLfO8AxGBq08lcJKs9B9drr9onA583UM7Uf7RIcjkZwA5ETPVb1yNF2QkNbVSUGLhKDv3OaRIbgs/CB5R4bAca5DK+8p4jNPnKNI4cDirJvDr/7tCMEkXfOZ84QC4UCegdUaexEgnheny1kgZ/1M8BzIsIE0o082cLrPWr7Wbu17P0i19J/jhkL8YIgVjvx0yU7abxUZYsNzQRWWNGpJapZHL3bvmMVkPdp7nBcS3tbHt3SHqMFDOUyVywk1O23q7ZNNFzx8ui9Og1tIWyYzZiSnxbo/r4gPLt8AgAYctRcIa3ahpFOiiN9iZbkVKcpREmX0HmgBo/AaMExgBg8onbi8KCbJWYV99t5e3Vu1xYeAHwxpVBoJjNyKPo5yQ0mrqLY6u3l+uDS785khX68039xufH7GPey4Af0k6z3sHVlkOVWKLiKEiQJcAaSJ9YeIE5HTNqdaBOvrQ3IQLnRJyHtlu4zShjhe+sR4DeCTp8MPKvNOk7QLQWgHFHb+zOtUuDY0bG6aF/S/sh0odG3CuniBxxHZLKwlv4DpIhxCdEdHpNX5AXG3eKpYMKLmNe8w/TIzQFmrXd9YoW2ZjVyLkDOS7FzlNTmxe8FWv3XVv8HUWDvzFW4wZkmzTM8=
      
      skip_cleanup: true
    
      file: $OUR_DIR/release/opencascade-$TRAVIS_TAG-linux-x64.zip
    
      on:
        condition: $TRAVIS_OS_NAME = linux
        tags: true
        #repo: miho/OCC-CSG
        
    - provider: releases
    
      api_key:
        secure: viIrz01hHL97XF1B2Dq37VkaOjaenpP0bWYXeFXBiCd6a1tBYLfO8AxGBq08lcJKs9B9drr9onA583UM7Uf7RIcjkZwA5ETPVb1yNF2QkNbVSUGLhKDv3OaRIbgs/CB5R4bAca5DK+8p4jNPnKNI4cDirJvDr/7tCMEkXfOZ84QC4UCegdUaexEgnheny1kgZ/1M8BzIsIE0o082cLrPWr7Wbu17P0i19J/jhkL8YIgVjvx0yU7abxUZYsNzQRWWNGpJapZHL3bvmMVkPdp7nBcS3tbHt3SHqMFDOUyVywk1O23q7ZNNFzx8ui9Og1tIWyYzZiSnxbo/r4gPLt8AgAYctRcIa3ahpFOiiN9iZbkVKcpREmX0HmgBo/AaMExgBg8onbi8KCbJWYV99t5e3Vu1xYeAHwxpVBoJjNyKPo5yQ0mrqLY6u3l+uDS785khX68039xufH7GPey4Af0k6z3sHVlkOVWKLiKEiQJcAaSJ9YeIE5HTNqdaBOvrQ3IQLnRJyHtlu4zShjhe+sR4DeCTp8MPKvNOk7QLQWgHFHb+zOtUuDY0bG6aF/S/sh0odG3CuniBxxHZLKwlv4DpIhxCdEdHpNX5AXG3eKpYMKLmNe8w/TIzQFmrXd9YoW2ZjVyLkDOS7FzlNTmxe8FWv3XVv8HUWDvzFW4wZkmzTM8=
      
      skip_cleanup: true
    
      file: $OUR_DIR/release/opencascade-$TRAVIS_TAG-macos.zip
    
      on:
        condition: $TRAVIS_OS_NAME = osx
        tags: true
        #repo: miho/OCC-CSG      
