sudo: false

addons:
    apt:
      packages:
       - make
       - cmake-data
       - cmake
       - libglu1-mesa-dev
       - libgl1-mesa-dev 

matrix:
    include:
    - os: linux
      language: c++
      install: true
    - os: osx
      language: c++
      osx_image: xcode9.2
      install: true

cache:
  ccache: true
  directories:
   - $HOME/Library/Caches/Homebrew
   ## TODO: how can we do conditional caching of directories (depending on OS)
   - /Users/travis/build/miho/occ-for-occ-csg/opencascade
   - /Users/travis/build/miho/occ-for-occ-csg/dependencies

env:
  global:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then PATH=/usr/lib/ccache:${PATH}; fi
    - TIMEOUT_BUILD='30m'
    - BUILD_SUCCESS=true
    
before_install:
  # installing ccache and freetype packages via homebrew
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ccache; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
  # adding timeout command to path for os x
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then PATH="$PATH:/usr/local/opt/coreutils/libexec/gnubin"; fi
  
script: 
    - export OUR_DIR=$(pwd)
    - echo "home directory $OUR_DIR"
    
    # downloading and building static freetype
    #- wget https://download.savannah.gnu.org/releases/freetype/freetype-2.7.1.tar.gz
    #- tar xzf freetype-2.7.1.tar.gz
    #- cd freetype-2.7.1; mkdir -p build; cd build;
    - mkdir -p $OUR_DIR/dependencies-installation/freetype
    - cd $OUR_DIR/dependencies/freetype  
    - mkdir -p build; cd build;
    - cmake .. -DWITH_ZLIB=OFF -DWITH_HarfBuzz=OFF -DWITH_PNG=OFF -DWITH_BZip2=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=$OUR_DIR/dependencies-installation/freetype;
    - make -j2 && make install
    - cd $OUR_DIR
    
    # downloading OCE
    #- if [ ! -f OCE-0.18.3.tar.gz ]; then wget https://github.com/miho/oce/archive/OCE-0.18.3.tar.gz; fi
    #- if [ ! -f oce-OCE-0.18.3 ]; then tar xzf OCE-0.18.3.tar.gz; fi
    #- cd oce-OCE-0.18.3
    - cd opencascade
    - mkdir -p build && mkdir -p $OUR_DIR/opencascade-installation && cd build
    
    # setting OCE install dir
    # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export OCE_INSTALL_DIR=$(pwd)/../opencascade-installation/OCE.framework/Versions/0.18/Resources; fi
    # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export OCE_INSTALL_DIR=$(pwd)/../opencascade-installation/lib/oce-0.18/; fi
    
    - rm -rf ./*
    
    # configuring OCE via cmake
    - cmake .. -DBUILD_LIBRARY_TYPE:String="Static" -DCMAKE_BUILD_TYPE=Release -DBUILD_MODULE_Draw:BOOL=false -D3RDPARTY_DIR=$OUR_DIR/dependencies-installation -DCMAKE_INSTALL_PREFIX=$OUR_DIR/opencascade-installation -DINSTALL_FREETYPE:BOOL=true -DFREETYPE_INCLUDE_DIRS=$OUR_DIR/dependencies-installation/freetype/include
    
    # now we build OCE
    # -> On macOS we use a timeout to prevent travis from terminating our build job
    #    without saving the ccache and OCE directories. We rerun the job until OCE
    #    is fully built. The output will indicate that by showing 
    #       ">> skipping build until ccache and compilation of oce works. restart task or schedule new task."
    #    TODO: is there a workaround for build jobs that take longer than 50 minutes?
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 30 make -j4 && make install > install_out.txt || export BUILD_SUCCESS=false ; fi
    # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 30 timeout -s SIGTERM $TIMEOUT_BUILD make -j4 install > install_out.txt || export BUILD_SUCCESS=false ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_wait 30 make -j8 && make install > install_out.txt || export BUILD_SUCCESS=false; fi
    # show last 30 lines of install output
    - tail -n 30 install_out.txt
    
    
    # finally build and test occ-csg
    #- cd $OUR_DIR
    #- mkdir -p build && cd build
    #- (! $BUILD_SUCCESS && echo ">> skipping build until ccache and compilation of oce works. restart task or schedule new task.") || cmake .. -DOCE_DIR=$OCE_INSTALL_DIR
    #- (! $BUILD_SUCCESS && echo ">> skipping build until ccache and compilation of oce works. restart task or schedule new task.") || make && bin/occ-csg --help       

before_deploy:
    - cd $OUR_DIR
    - mkdir release && cd release
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir -p opencascade-$TRAVIS_TAG-macos/; cp -r $OUR_DIR/opencascade-installation/* opencascade-$TRAVIS_TAG-macos; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then zip -r opencascade-$TRAVIS_TAG-macos.zip opencascade-$TRAVIS_TAG-macos/; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir -p opencascade-$TRAVIS_TAG-linux-x64/; cp $OUR_DIR/opencascade-installation/* opencascade-$TRAVIS_TAG-linux-x64/; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then zip -r opencascade-$TRAVIS_TAG-linux-x64.zip opencascade-$TRAVIS_TAG-linux-x64/; fi   

deploy:
    - provider: releases
    
      api_key:
        secure: zjSgPQIowqYPUILskt3+Bn1+wfvJsIQz4INZbusPRMCJvLchQzIxvejURPqb7f067cDbHXFoUjGydgHz6WdIFhp31scML5816enBTQeVOgKwc3cLlV2FY9i/ymxckF7fnJ0DTyz6f99bGx8oQSglNfiyOt8JO6pYzB7ZpEQaGByqyYiBsXGjAEauezbux1jNPo5B8yt4cwfy/uH9RvCpNMXgbJSFqm87nfrovAbzVda6hjLPWeY7AmP3aO9Vv0YL7nYXrbyYLYkyO/lKz87jVCvxWW03rDo+5oAfCcZJAQ/4+Mhek6YeiqWC+kg7V35xRlbt6l5VJnB1UFQTnNXbvPps7EM0c0/0O4mBcMegIojdvApNV4U960ssa4e2jekhP6TsLBuPgwasoh7lYFWcX5IqtEbtJAKTBIO7ghPnSbLQmcrx57cTghFX8lJJVJsYSWOzKs5FZv3XdtKqK6fwqR3icjwTkuVuiTCn1/uXu8KCnTyyMhXKaLMZw0a5dP9MH4ZRNmFD8X5i9ZdLdV0e9T05GHSj7vNy9+dNi6AGX0j18LSrlnw9FDCkRk2YtWA5T/oSoJ8WEYa/i/2S30propGJt2xtN+2qW8QBq23zquNleh1VZwy31imXPlTx3r5ZQWNKE3hBWLnmoY87qkaIk0jZqX6bWw+KUleNT7lfIfk=
      
      skip_cleanup: true
    
      file: $OUR_DIR/release/opencascade-$TRAVIS_TAG-linux-x64.zip
    
      on:
        condition: $TRAVIS_OS_NAME = linux
        tags: true
        #repo: miho/OCC-CSG
        
    - provider: releases
    
      api_key:
        secure: zjSgPQIowqYPUILskt3+Bn1+wfvJsIQz4INZbusPRMCJvLchQzIxvejURPqb7f067cDbHXFoUjGydgHz6WdIFhp31scML5816enBTQeVOgKwc3cLlV2FY9i/ymxckF7fnJ0DTyz6f99bGx8oQSglNfiyOt8JO6pYzB7ZpEQaGByqyYiBsXGjAEauezbux1jNPo5B8yt4cwfy/uH9RvCpNMXgbJSFqm87nfrovAbzVda6hjLPWeY7AmP3aO9Vv0YL7nYXrbyYLYkyO/lKz87jVCvxWW03rDo+5oAfCcZJAQ/4+Mhek6YeiqWC+kg7V35xRlbt6l5VJnB1UFQTnNXbvPps7EM0c0/0O4mBcMegIojdvApNV4U960ssa4e2jekhP6TsLBuPgwasoh7lYFWcX5IqtEbtJAKTBIO7ghPnSbLQmcrx57cTghFX8lJJVJsYSWOzKs5FZv3XdtKqK6fwqR3icjwTkuVuiTCn1/uXu8KCnTyyMhXKaLMZw0a5dP9MH4ZRNmFD8X5i9ZdLdV0e9T05GHSj7vNy9+dNi6AGX0j18LSrlnw9FDCkRk2YtWA5T/oSoJ8WEYa/i/2S30propGJt2xtN+2qW8QBq23zquNleh1VZwy31imXPlTx3r5ZQWNKE3hBWLnmoY87qkaIk0jZqX6bWw+KUleNT7lfIfk=
      
      skip_cleanup: true
    
      file: $OUR_DIR/release/opencascade-$TRAVIS_TAG-macos.zip
    
      on:
        condition: $TRAVIS_OS_NAME = osx
        tags: true
        #repo: miho/OCC-CSG      
