
# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - date /T & time /T
  - git config --global core.autocrlf input
  - cmake --version

#branches:
#  only:
#  - master

clone_depth: 5

version: '{build}'

platform:
  - x64

configuration:
  - Release

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
    - generator: "Visual Studio 15 2017 Win64"    

matrix:
  fast_finish: true

cache:
  - C:\projects\occ-for-occ-csg\dependencies\
  - C:\projects\occ-for-occ-csg\opencascade\

build_script:
  - vswhere -property installationPath
  
  # find installation dir, replacement for %VS150COMNTOOLS%
  - |-
       REM crappy windows batch replacement for bash's var=`mycommand` 
       for /f "usebackq tokens=*" %%a in (`vswhere -property installationPath`) do set InstallDir=%%a
      
       echo %InstallDir%\VC\Auxiliary\Build\
       
       dir "%InstallDir%\VC\Auxiliary\Build\"
  
       REM if exist "%InstallDir%\VC\Auxiliary\Build\Microsoft.VCRedistVersion.default.txt" (
         set /p RedistVersion=<"%InstallDir%\VC\Auxiliary\Build\Microsoft.VCRedistVersion.default.txt"
       REM )
       
       echo "%InstallDir%\VC\Redist\MSVC\%RedistVersion%\"
       dir "%InstallDir%\VC\Redist\MSVC\%RedistVersion%\"
       set "REDIST_DIR=%InstallDir%\VC\Redist\MSVC\%RedistVersion%\"
     
  
  - echo %VS150COMNTOOLS%
     
  # install FreeType 2.7.1
  #- curl -LfsS -o freetype-2.7.1.tar.gz https://download.savannah.gnu.org/releases/freetype/freetype-2.7.1.tar.gz
  #- cmd.exe '/C 7z x "freetype-2.7.1.tar.gz" -so | 7z x -aoa -si -ttar -o%APPVEYOR_BUILD_FOLDER%\freetype-2.7.1 -y > nul
  - cd %APPVEYOR_BUILD_FOLDER%\dependencies\freetype
  - dir
  - if not exist build mkdir build
  - if not exist %APPVEYOR_BUILD_FOLDER%\dependencies-installation\ mkdir %APPVEYOR_BUILD_FOLDER%\dependencies-installation
  - if not exist %APPVEYOR_BUILD_FOLDER%\dependencies-installation\freetype mkdir %APPVEYOR_BUILD_FOLDER%\dependencies-installation\freetype
  - cd build
  - cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS:BOOL=false -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\dependencies-installation\freetype
  - MSBuild .\INSTALL.vcxproj  /property:Configuration=Release /property:Platform=x64
  
  - dir %APPVEYOR_BUILD_FOLDER%\dependencies-installation
  
  # install OCE 0.18.3 
  #- curl -LfsS -o OCE-0.18.3.tar.gz https://github.com/miho/oce/archive/OCE-0.18.3.tar.gz
  #- cmd.exe '/C 7z x "OCE-0.18.3.tar.gz" -so | 7z x -aoa -si -ttar -o%APPVEYOR_BUILD_FOLDER%\OCE-0.18.3 -y > nul
  #- cd %APPVEYOR_BUILD_FOLDER%\
  #- if not exist occ git clone --branch OCE-0.18.3 --depth 1 https://github.com/tpaviot/oce.git oce
  #- git clone https://github.com/tpaviot/oce.git oce
  #- cd %APPVEYOR_BUILD_FOLDER%\
  - dir
  - cd %APPVEYOR_BUILD_FOLDER%\opencascade
  #- git checkout OCE-0.18.3
  - dir
  - if not exist build mkdir build
  - if not exist %APPVEYOR_BUILD_FOLDER%\opencascade-installation mkdir %APPVEYOR_BUILD_FOLDER%\opencascade-installation
  - cd build
  - cmake .. -G "Visual Studio 15 2017 Win64" -DBUILD_LIBRARY_TYPE:String="Static" -DCMAKE_BUILD_TYPE=Release -DBUILD_MODULE_Draw:BOOL=false -D3RDPARTY_DIR=%APPVEYOR_BUILD_FOLDER%\dependencies-installation -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\opencascade-installation" -DINSTALL_FREETYPE:BOOL=true
  - MSBuild .\INSTALL.vcxproj  /property:Configuration=Release /property:Platform=x64

after_build:
  # create folder structure for release
  - if not exist %APPVEYOR_BUILD_FOLDER%\release mkdir %APPVEYOR_BUILD_FOLDER%\release
  - if not exist %APPVEYOR_BUILD_FOLDER%\release\opencascade-%APPVEYOR_REPO_TAG_NAME%-windows-x64 rmdir /S /Q %APPVEYOR_BUILD_FOLDER%\release\opencascade-%APPVEYOR_REPO_TAG_NAME%-windows-x64
  
  - xcopy %APPVEYOR_BUILD_FOLDER%\opencascade-installation %APPVEYOR_BUILD_FOLDER%\release\opencascade-%APPVEYOR_REPO_TAG_NAME%-windows-x64 /e /i /h
  
  # package the release
  - 7z a -tzip %APPVEYOR_BUILD_FOLDER%\release\opencascade-%APPVEYOR_REPO_TAG_NAME%-windows-x64.zip %APPVEYOR_BUILD_FOLDER%\release\opencascade-%APPVEYOR_REPO_TAG_NAME%-windows-x64\
  
  # push final release archive as artifact
  - appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\release\opencascade-%APPVEYOR_REPO_TAG_NAME%-windows-x64.zip
  

deploy:

  - provider: GitHub
    name: production
    
    on:
      appveyor_repo_tag: true
      
    auth_token:
      secure: R+KuFwD7fxyhPRJUEDg4raWGX1H4NZiEN1LM74aADv8pCa3Rz0CXzKBixMK8gxwQ
      
    # artifact: %APPVEYOR_BUILD_FOLDER%\release\occ-csg-%APPVEYOR_REPO_TAG_NAME%-windows-x64.zip
